audit:
	yarn audit --groups "dependencies"

build:
	yarn run build

install:
	yarn --check-files

lint:
	yarn lint

prettier:
	yarn prettier --write .

run:
	yarn start

serve:
	npx serve -s build

test:
	yarn test
